openapi: '3.0.0'
description: 'Định nghĩa các parameters dùng chung.'
info:
  title: 'Parameters common'
  version: '1.0'
tags:
  - Common
components:
  parameters:
    offset:
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
      description: 'Số bản ghi bỏ qua để bắt đầu lấy danh sách trả về. Sử dụng cho phân trang.'
    limit:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 500
        default: 20
      description: 'Giới hạn số bản ghi trả về. Mặc định là 20 và max là 100.'